server:
  port: 8081

spring:
  application:
    name: routeitApi
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate.jdbc.batch_size: 50
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    defer-datasource-initialization: true # script 파일이 hibernate 초기화 이후 동작
#  sql:
#    init:
#      data-locations: classpath:sql/initData.sql # init data file path
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  messages:
    basename: message/messages
    encoding: UTF-8
    fallback-to-system-locale: true # 요청받은 Locale에 대한 파일을 찾지 못할 경우 시스템 설정 Locale을 사용

springdoc:
  api-docs:
    path: /api-docs # default : /v3/api-docs
    enabled: true
  default-consumes-media-type: application/json # request media type
  default-produces-media-type: application/json # response media type
  swagger-ui:
    path: /
    tags-sorter: alpha
    operations-sorter: alpha
    disable-swagger-default-url: true # swagger-ui default url 비활성화 (pet, store..)
  packages-to-scan: com.routeit.routeitapi.application
  #paths-to-match: /**/controller

jwt:
  secret: cm91dGVpdGp3dGtleXRhZXlhbmc=cm91dGVpdGp3dGtleXRhZXlhbmc=