server:
  port: 8081

spring:
  application:
    name: routeitApi
  h2:
    console: # h2 console
      enabled: true
      path: /h2-console # h2 console path
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:routeit #in-memory
    #url: jdbc:h2:./h2-database #local
    username: routeit
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create # drop table if exists
      #ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate.jdbc.batch_size: 50
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate:
        use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true # 쿼리 로그
        format_sql: true # 쿼리 로그 포맷팅
        highlight_sql: true # 쿼리 로그 예약어들 하이라이팅
    defer-datasource-initialization: true # script 파일이 hibernate 초기화 이후 동작
#  sql:
#    init:
#      data-locations: classpath:sql/initData.sql # init data file path
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      host: localhost
      port: 27017
      database: routeit
  devtools:
    restart:
      enabled: false
  messages:
    basename: message/messages
    encoding: UTF-8
    fallback-to-system-locale: true # 요청받은 Locale에 대한 파일을 찾지 못할 경우 시스템 설정 Locale을 사용

springdoc:
  api-docs:
    path: /api-docs # default : /v3/api-docs
    enabled: true
  default-consumes-media-type: application/json # request media type
  default-produces-media-type: application/json # response media type
  swagger-ui:
    path: /
    tags-sorter: alpha
    operations-sorter: alpha
    disable-swagger-default-url: true # swagger-ui default url 비활성화 (pet, store..)
  packages-to-scan: com.routeit.routeitapi.application
  #paths-to-match: /**/controller

jwt:
  secret: cm91dGVpdGp3dGtleXRhZXlhbmc=cm91dGVpdGp3dGtleXRhZXlhbmc=

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE
        SQL: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.data.mongodb.core.MongoOperations: DEBUG
    org.springframework.data.mongodb.core.SimpleMongoClientDatabaseFactory: DEBUG